import { redirect } from 'next/navigation'
import { getSession } from '@/lib/auth'
import { getProductByPlanType } from '@/lib/products'
import { BriefingDisplay } from '@/components/dashboard/briefing-display'
import { DashboardHeader } from '@/components/dashboard/dashboard-header'

export default async function DashboardPage() {
  const session = await getSession()

  if (!session || !session.subscription) {
    redirect('/subscribe')
  }

  const { user, subscription } = session
  const product = getProductByPlanType(subscription.plan)

  // Calculate volume and issue number based on date
  const today = new Date()
  const startDate = new Date('2024-01-01')
  const daysSinceStart = Math.floor((today.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24))
  const issueNumber = daysSinceStart + 1
  const volume = Math.floor(daysSinceStart / 365) + 3

  const formattedDate = today.toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })

  return (
    <div className="paper-texture min-h-screen">
      <DashboardHeader 
        email={user.email} 
        planName={product?.name || 'Subscriber'}
      />
      
      <main className="max-w-5xl mx-auto px-6 py-8">
        {/* Masthead */}
        <header className="text-center mb-8">
          <div className="rule-double pb-6 mb-6">
            <p className="text-xs tracking-[0.3em] text-muted-foreground mb-2 uppercase">
              {formattedDate}
            </p>
          </div>
          
          <h1 className="masthead text-4xl md:text-5xl font-serif font-semibold tracking-wider mb-4">
            The Morning Tape
          </h1>
          
          <p className="text-sm tracking-[0.2em] text-muted-foreground font-serif">
            Vol. {toRoman(volume)} · No. {issueNumber}
          </p>
          
          <div className="rule-double mt-6 pt-1" />
        </header>

        {/* Briefing Content */}
        <BriefingDisplay plan={subscription.plan} />
        
        {/* Footer */}
        <footer className="mt-16 pt-8 border-t border-border text-center">
          <p className="text-xs text-muted-foreground">
            &copy; {new Date().getFullYear()} The Morning Tape. All rights reserved.
          </p>
          <p className="text-xs text-muted-foreground mt-1">
            This briefing is generated by AI and is for informational purposes only. 
            It does not constitute financial advice.
          </p>
        </footer>
      </main>
    </div>
  )
}

function toRoman(num: number): string {
  const romanNumerals: [number, string][] = [
    [10, 'X'],
    [9, 'IX'],
    [5, 'V'],
    [4, 'IV'],
    [1, 'I'],
  ]
  
  let result = ''
  let remaining = num
  
  for (const [value, symbol] of romanNumerals) {
    while (remaining >= value) {
      result += symbol
      remaining -= value
    }
  }
  
  return result
}
